### ISSUE TITLE
Text proposal dependency on harfbuzz

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/OpenUSD-proposals#51]
@PierreWang wrote

> Q: And if harfbuzz is used, does that mean it becomes a dependency on usd/hydra?
> A: Yes, if you build USD together with the default text plugins, harfbuzz will be a dependency. So we have added the build configuration "--textplugin". By default the config is off, so the plugins will not be built, and FreeType and harfbuzz are not required. If you turn on this config, the default text plugins will be built together with USD.

@meshula wrote

> harfbuzz; is it possible to make it optional? i.e. provide a fallback layout based on elementary glyph metrics and kerning?

**Comment by PierreWang** [comment]
My answer in the proposal discussion: Yes. A fallback layout should be provided.

**Comment by meshula** [comment]
Cooll :) I'll close this issue as resolved.
